/* > Guardbands */
#ifndef CAR_REMOTE_H
#define CAR_REMOTE_H

/* > Outer libraries include */
#include <IRremote.h>

/* Defines */
#define CAR_REMOTE_CODE_UNKNOWN (-1)

#define CAR_REMOTE_CODE_ZERO        CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_ONE         CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_TWO         CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_THREE       CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_FOUR        CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_FIVE        CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_SIX         CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_SEVEN       CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_EIGHT       CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_NINE        CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_STAR        CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_HASH        CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_OK          CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_UPARR       CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_DOWNARR     CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_LEFTARR     CAR_REMOTE_CODE_UNKNOWN
#define CAR_REMOTE_CODE_RIGHTARR    CAR_REMOTE_CODE_UNKNOWN

#endif /* CAR_REMOTE_H */